### ISSUE TITLE
【bug】查看笔记时图片有字体问题

### ISSUE THREAD

**Issue by Ikaros-521** [Passerby-D/nonebot_plugin_note#4]
`/记事 ¡El pueblo unido jamás será vencido!`
![image](https://user-images.githubusercontent.com/40910637/204331395-47749348-1f33-4fb9-869d-7c891bab01cb.png)

**Comment by Passerby-D** [comment]
感谢指出问题
这个是什么特殊字符吗，好像是PIL里的imagedraw不能识别，我也不太清楚应该怎么改
不过一般记事应该不会用到，应该不会影响正常使用吧（

**Comment by Ikaros-521** [comment]
确实 群友喜欢测试些稀奇古怪的。感觉可以给笔记加一个下标标注。输入原文进行删除感觉有点麻烦。（不过这样的话，需要改挺多www）
