### ISSUE TITLE
还是缺少这个啊,重新卸载安装了

### ISSUE THREAD

**Issue by bowen99** [Passerby-D/nonebot_plugin_note#6]
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\bowen_wang\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\nonebot_pl
ugin_note\\data\\list.png'

**Comment by bowen99** [comment]
> File "C:\Users\bowen_wang\AppData\Local\Programs\Python\Python39\lib\site-packages\apscheduler\executors\base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "C:\Users\bowen_wang\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot_plugin_note\__init__.py", line 408, in _restart
    await nonebot.get_bot().send_private_msg(user_id=superuser,message=Message("已成功重启所有的记事项目"))
  File "C:\Users\bowen_wang\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\__init__.py", line 160, in get_bot
    raise ValueError("There are no bots to get.")
ValueError: There are no bots to get.

**Comment by Ikaros-521** [comment]
> FileNotFoundError: [Errno 2] No such file or directory: 'C:\Users\bowen_wang\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot_pl ugin_note\data\list.png'

作者还没重新打包发布吧。可以手动替换下__init__.py的源码

**Comment by Passerby-D** [comment]
嘶，我应该重新打包发布过了，你是通过什么方式安装的，或者现在再试试呢



> FileNotFoundError: [Errno 2] No such file or directory: 'C:\Users\bowen_wang\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot_pl ugin_note\data\list.png'

**Comment by Passerby-D** [comment]
> > File "C:\Users\bowen_wang\AppData\Local\Programs\Python\Python39\lib\site-packages\apscheduler\executors\base_py3.py", line 30, in run_coroutine_job
> > retval = await job.func(*job.args, **job.kwargs)
> > File "C:\Users\bowen_wang\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot_plugin_note__init__.py", line 408, in _restart
> > await nonebot.get_bot().send_private_msg(user_id=superuser,message=Message("已成功重启所有的记事项目"))
> > File "C:\Users\bowen_wang\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot__init__.py", line 160, in get_bot
> > raise ValueError("There are no bots to get.")
> > ValueError: There are no bots to get.

这个是自动重启之前的记事项目，等到bot启动成功就可以了

**Comment by Ikaros-521** [comment]
> > > File "C:\Users\bowen_wang\AppData\Local\Programs\Python\Python39\lib\site-packages\apscheduler\executors\base_py3.py", line 30, in run_coroutine_job
> > > retval = await job.func(*job.args, **job.kwargs)
> > > File "C:\Users\bowen_wang\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot_plugin_note__init__.py", line 408, in _restart
> > > await nonebot.get_bot().send_private_msg(user_id=superuser,message=Message("已成功重启所有的记事项目"))
> > > File "C:\Users\bowen_wang\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot__init__.py", line 160, in get_bot
> > > raise ValueError("There are no bots to get.")
> > > ValueError: There are no bots to get.
> 
> 这个是自动重启之前的记事项目，等到bot启动成功就可以了

480+行那里感觉还是稍微加个异常捕获比较好，报错噶噶的看着怪难受的
```
        try:
            await nonebot.get_bot().send_private_msg(user_id=superuser,message=Message("已成功重启所有的记事项目"))
            timing.remove_job(job_id='restart')
        except:
            nonebot.logger.info("There are no bots to get.")
```

**Comment by Passerby-D** [comment]
确实，之前没想到，下次更新顺便带上

**Comment by Ikaros-521** [comment]
> 确实，之前没想到，下次更新顺便带上

帅者的肯定.jpg
