### ISSUE TITLE
貌似是PIL打开字体错误了，是Centos7的环境

### ISSUE THREAD

**Issue by anlen123** [Passerby-D/nonebot_plugin_note#8]
![image](https://user-images.githubusercontent.com/49887895/204759749-bb7c0172-e60f-4033-89b9-80c9ee3983ff.png)

**Comment by Passerby-D** [comment]
感谢提出问题

但是linux我没怎么用过，是linux里的字体名字和windows的不太一样吗，要是你想换字体可以把CreateMutiLinesPic函数里的‘simkai.ttf’换成你想要的试试看
如果是PIL的问题的话我暂时也没什么头绪

可以先在env里设置note_type='text'用文本回复
